services:
  # 1. Database
  db:
    image: postgres:15-alpine
    container_name: chat-app-db
    restart: always
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: chatapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chat-network

  # 2. Backend
  backend:
    build: ./backend
    container_name: chat-app-backend
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # Kết nối nội bộ Docker dùng 'db' thay vì 'localhost'
      DATABASE_URL: "postgresql://chatapp:1234@db:5432/chatapp_db?schema=public"
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      EMAIL_USER: ${EMAIL_USER}
      EMAIL_PASS: ${EMAIL_PASS}
    depends_on:
      - db
    networks:
      - chat-network

  # 3. Frontend
  frontend:
    build: ./frontend
    container_name: chat-app-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - chat-network

volumes:
  postgres_data:

networks:
  chat-network:
    driver: bridge